### ISSUE TITLE
Prerotator auto-off

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/PX4Firmware#10]
Zatím se prerotátor vypne při dosažení rychlosti nastavené v parametru 'RW_PREROT_MAXSPD'. Zde by to chtělo udělat nějaké škálování rychlosti, aby to nebylo okamžité a kontrolu, že je letadlo na zemi.

**Comment by kaklik** [comment]
No on se prerotátor může vypnout myslím snad i skokově.  Protože je to v podstatě pojistka před tím, aby se nevzlétalo se zapnutým prerotátorem. 

Co se stane, když airspeed klesne pod rozhodovací úroveň RW_PREROT_MAXSPD, není možné, že se prerotátor pak neočekávaně zase zapne?

**Comment by roman-dvorak** [comment]
Tato funkce bude součástí #21
