### ISSUE TITLE
Automatické odpojení vlečného lana

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/PX4Firmware#20]
Při provádění vzletu na laně je potřebné, aby lano mohlo být odpojeno jak od pilota vírníku, tak i od vlečného auta.  V běžném letovém provozu se tato záležitost řeší odpojovačem na obou koncích lana. 

Pro naše použití je pravděpodobně nepřípustné, aby bylo lano odpojeno od vlečného auta. Proto je nutné vyřešit vzdálené odpojování z tažného auta [TF-R1](https://github.com/ThunderFly-aerospace/TF-R1). Odpojení od auta by mělo nastat v chybových stavech během vzletu: 

- Neočekávaná překážka na dráze
- Ztráta výkonu tahu 
- Ztráta rychlosti vlečného auta
- Propnutí vlečného lana
- Přetržení vlečného lana. 

Ve těchto případech by mělo dojít k automatickému odpojení lana a ke spuštění vlastního pohonu vírníku. Následující seznam jsou chybové stavy, které mohou nastat před startem. 

- Nedostatečné otáčky rotoru vírníku po roztočení rotoru 
- Lano je povoloné, ale byl zahájen rozjezd
- Dojde k ochlazení/vybití akumulátorů

Samotný povel odpojení je nutné přenést do vírníku telemetrickým modemem přes mavlink. Protože odpojovač se ovládá servem připojeným na PWM kanál autopilota, tak jsou dvě možnosti typu přenosu signálu pro odpojení 

1. Přepsání hodnoty PWM výstupu [RC_CHANNELS_OVERRIDE](https://mavlink.io/en/messages/common.html#PARACHUTE_ACTION)
2. [Přepínání módů letu](https://docs.px4.io/v1.9.0/en/getting_started/flight_modes.html) 

Obě metody zřejmě umožňují, aby pilot vírníku odpojil vlečné lano.   Hlavní rozdíl je pravděpodobně v tom ze první metoda nijak nezmění režim letu a autopilot ani pilot na odpojení nemůže kvalitně zareagovat. 

Jako vhodnější tak vypadá využití druhé metody, kdy se zároveň s odpojením lana změní režim autopilota a způsob řízení vírníku.

**Comment by roman-dvorak** [comment]
Aktuálně se nepočítá se startem z lana. Je to zbytečně riskantní způsob startu.
