### ISSUE TITLE
Unhandled case of FlightGear supported a subset of the models

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/PX4Firmware#22]
sitl_run.sh script does not handle [a case of unsupported models](https://github.com/PX4/Firmware/pull/14539#discussion_r400792391).

**Comment by slimonslimon** [comment]
Exactly - not sitl_run.sh but sitl_targets.cmake

**Comment by slimonslimon** [comment]
Fixed in PR.
