### ISSUE TITLE
Úprava odpojovacího kontroléru

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/PX4Firmware#27]
Odpojovací asistent by bylo vhodné upravit tak, aby byl přijat do upstreamu. Což znamená, že musí být pochopitelně užitečný i pro ostatní uživatele. V tomto případě by to zřejmě mohla být pomoc zejména při startu z ruky. 

- [x] Podmínka pitch_setpoint pro odpojení
- [x] Přímé ovládání v disarmovaném stavu
- [x] Pípání
- [x] Poslání příkazu k odpojení přes MAVLink

Odpojovací kontrolér nyní hlídá 4 podmínky, které musí být splněné pro odeslání požadavku na odpojení. Těmi jsou:

- povolení z RC ovladače
- minimální airspeed 
- minimální RPM a přípust motoru nad polovinu. 

### Kontrola attitude setpointu

Bylo by potřeba přidat podmínku, která bude vírník odpojovat při attitude_setpointu v určitém rozsahu okolo vyrovnané polohy a do výpisu vypisovat aktuální nastavení/hodnoty. 

Cílem je, aby po vypuštění nemohl vírník nečekaně převrátit přes záda, nebo se naklonit (při roll setpointu). 

### Ovládání v disaarmovaném stavu
Dalším vylepšením by bylo, aby bylo možné platformu odpojit připojit nějak kontrolovaně elektronicky. Mělo by to být udělat tak, že pokud je vírník DISARMovaný, tak přepnutí vypínače bude přímo ovládat výstup platformy. 

### Zvuková signalizace stavů
Zejména pro start z ruky by bylo výhodné, kdyby asistent signalizoval splnění jednotlivých podmínek.  Například tím že by při každém dalším splnění podmínky krátce pípnul. Při splnění všech podmínek by pípl dlouze (podobně jako se ohlašuje přesný čas v rádiu).
Zde by mohlo být rozlišeno zda podmínka stále platí nebo již ne. Například tím že splnění podmínky je vysoký tón a pominutí podmínky naopak nízký. 

Při vysokém počtu podmínek by  ale pípání při každé z nich mohlo být matoucí. Bylo by tak vhodné, kdyby každé podmínce bylo možné aktivovat, nebo naopak deaktivovat zvukovou signalizaci. 

Pro zvukovou signalizaci je také důležité, aby použitý zvuk byl typický pro startovní sekvenci a nevyužíval zvuky které vírník běžně dělá během příprav ke startu. 

### Vygenerování příkazu k odpojení 

Pro některé způsoby startu by bylo praktické, kdyby UAV mohlo poslat příkaz k odpojení. V případě vírníku je to například uvolnění z platformy po dosažení letového stavu.  Mavlink zdá se zatím nebsahuje packet, který by byl vhodný přímo pro toto použití. Nicméně obsahuje příkaz [MAV_CMD_NAV_TAKEOFF](https://mavlink.io/en/messages/common.html#MAV_CMD_NAV_TAKEOFF), který je původně určený pro start UAV. Zřejmě by je jej momhla využít i pozemní stanice pro uvolnění UAV z platformy.

**Comment by kaklik** [comment]
Poslední úprava odpojovacího kontroleru způsobila, že bylo zrušeno palubní logování tunnel packetu.

**Comment by kaklik** [comment]
Nový firmware logování v kombinaci s odpojovacím kontrolerem pravděpodobně opravil.   Potíž ale nastavá s faktem, že zřejmě nestačí, aby celý proces startu končil signálem pro odpojení. 
Na základě posledních pokusů je zde poměrně významný požadavek na přechod do režimu maximálního stoupání a zafixování letového stavu (stabilizace otáček rotoru, stabilizace rychlosti a polohy). Neboť těsně po vypuštění je vírník citlivý na chyby regulátoru i pilotážní chyby, což může mít snadno za následek havárii.

**Comment by kaklik** [comment]
Zde je práce také velmi hotová. Zbývá nahradit provizorní mavlink zprávu CAMERA_IMAGE_CAPTURED, některou, která bude akceptovatelná v PX4 pull-requestu.

**Comment by roman-dvorak** [comment]
V mavlinku jsem aktuálně nenašel žádnou vhodnou zprávu. 

Navrhoval bych zprávu prozatím nahradit zprávou: https://mavlink.io/en/messages/common.html#DEBUG Po dokončení PR pak vytvořit vlastní zprávu pro tento způsob startu.

**Comment by kaklik** [comment]
> V mavlinku jsem aktuálně nenašel žádnou vhodnou zprávu.
> 
> Navrhoval bych zprávu prozatím nahradit zprávou: https://mavlink.io/en/messages/common.html#DEBUG Po dokončení PR pak vytvořit vlastní zprávu pro tento způsob startu.

Ok.. A myslíš, že je pak špatný nápad používat ty zprávy winch actions?

**Comment by roman-dvorak** [comment]
Tohle už není aktuální issue, je to řešeno v trochu jiné podobě součástí #32
