### ISSUE TITLE
TFRPM01 could wrongly report negative RPM in some cases

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/PX4Firmware#29]
Here is a graph showing that situation. 

![bokeh_plot(24)](https://user-images.githubusercontent.com/1194177/100550287-3b2a6d80-3279-11eb-9b74-487ad348cb09.png)

It is probably related to an unusual situation like a crash. It should be inspected and the suspicious conditions should be defined to avoid that.

**Comment by slimonslimon** [comment]
It needs "imaginal experimet" and code random walk to solve this issue...

**Comment by roman-dvorak** [comment]
it occurred, probably, at the moment when wires were broken down.

**Comment by kaklik** [comment]
The intensity of occurrence of this bug dramatically increased in combination with TFASPDIMU sensor connected at the same bus as is described in the comment: https://github.com/ThunderFly-aerospace/TF-G2/issues/88#issuecomment-785433829

**Comment by slimonslimon** [comment]
I don know how it can occured, but it will be detect as driver error and sensor will be restarted.

**Comment by roman-dvorak** [comment]
Negativní hodonty nyní reportovány nejsou. Aktuální nedostatek je, že driver povolí reportování extrémního peaku v kladných hodontách. 

@slimonslimon  narhuje to vyřešit způsobem, že se bude počítat něco jako aktuální derivace a na základě toho se rozhodne, jestli se hodnoty zahodí. 

Napadlo mne, zkusit vyčítat senzor 2x rychle za sebou a hodonty vzájemně porovnat. Jestli peak nevzniká způsobem, že v průběhu vyčítání všech registrů se změní hodnota některého bitu a tím vznikne taková extrémní hodnota. Z datasheetu není zřejmé, že by takováhle záležitost byla řešena.

**Comment by kaklik** [comment]
Navrhoval bych zlepšování tohodle issue nechat už na někom dalším. Pro naše použití je to myslím takhle už dostatečné.
