### ISSUE TITLE
Blikání ALERT ledky TFHT. 

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/PX4Firmware#39]
Při posledních pokusech bylo pozorováno blikání ALERT ledky, které nebylo nikdy dříve pozorováno a nikdy nebylo pozorováno v "laboratorních" podmínkách. ALERT může být spuštěn na základě několka stavů. Jednimi z nich jsou rozsahy měřené vlhkosti/teploty, která při posledních pokusech mohla být překročena. Driver si ALERT stav kontroluje a při jeho nastavení ho pak vymaže. Senzor zpět spadne do ALERT stavu. Díky tomu bylo pozorováno "blikání" alert ledky. 

V kombinaci s problémem https://github.com/ThunderFly-aerospace/TFHT01/issues/7, tak mohlo dojít ke špatnému měření teploty v době, kdy meteorologické podmínky byly mimo vyznačený rozsah:

![obrazek](https://user-images.githubusercontent.com/5196729/158229037-e25c5120-c8da-4673-ab0c-024f5904d2b8.png)
 

O nastavování těchto limitů se v základním datasheetu nic nepíše. Je k tomu application note, který ukazuje, jak si nastavit vlastní meze - tedy je nastavit na měřící rozsah senzoru. Application note je zde: https://www.mouser.com/pdfDocs/Sensirion_Humidity_Sensors_SHT3x_Application_Note_Alert_Mode_DIS.pdf

**Comment by kaklik** [comment]
Vyřešeno přenastavením ALERT hodnot do maximálních měřených.
